### ISSUE TITLE
general all-purpose flood control

### ISSUE THREAD

**Issue by jonorthwash** [apertium/phenny#252] opened 2017-08-01 16:35 UTC
Some modules (mailing list, commit messages, etc.) when they get behind might try to post dozens of updates at a time.  These end up more or less flooding a channel.  In these cases, it should post at most three messages: e.g., the earliest update, a message that says "...", and the latest update.

**Comment by jonorthwash** [comment] 2017-10-29 19:41
Perhaps related to #232 and #159.

**Comment by wei2912** [comment] 2017-11-30 16:46
Also related to https://github.com/goavki/phenny/issues/236.

**Comment by Androbin** [comment] 2017-12-27 00:53
This could either be a pure duplicate of #159 or we could intercept all calls to `phenny.msg` and thus have a "general all-purpose flood control". The latter doesn't seem quite right, thou.

Since we don't wanna break things, we could give `phenny.msg` a defaulted parameter to indicate if flood control should be applied or if the calling side knowns what it's doing.

**Comment by wei2912** [comment] 2017-12-27 06:42
Flood control should be module specific. There are times when information
should not be suppressed by an automatic filter, but rather, left to the
discretion of the module.

A solution to #159 should be adequate to address the issue.

**Comment by Androbin** [comment] 2017-12-29 01:59
@wei2912 Let's close this as a duplicate then?

**Closed** 2018-03-16 22:35 UTC
Labels: duplicate, enhancement

**Comment by jonorthwash** [comment] 2018-03-17 03:38
What issue is this a duplicate of?

**Comment by Androbin** [comment] 2018-03-17 12:06
See the last two comments.
