### ISSUE TITLE
check_mail reports all new mail at once

### ISSUE THREAD

**Issue by jonorthwash** [apertium/phenny#259] opened 2017-11-09 03:04 UTC
Usually begiak doesn't seem to report on new mail messages.  But when begiak is restarted and rejoins the room, it waits a few minutes and then floods the channel with all new mail.

**Comment by Androbin** [comment] 2017-12-23 15:35
What should be the desired behavior?
* Report continuously
* Don't report at all

**Comment by Androbin** [comment] 2017-12-23 15:40
Is #249 known to include any other message-related issues?

**Comment by shardulc** [comment] 2017-12-23 17:55
@Androbin Expected behavior is "report continuously". Also, how is #249 relevant?

**Comment by Androbin** [comment] 2017-12-23 18:15
> Also, how is #249 relevant?

@shardulc Since the mail check seems to be executed on module load and #249 is about the question of when certain code is executed, I thought it would be good to know if there are other related quirks.

**Comment by shardulc** [comment] 2017-12-23 18:19
@Androbin Hm, I would say reloading is a different case from what is probably affecting the mail module. But do look into it if you see a connection that would solve both issues.

**Comment by Androbin** [comment] 2017-12-23 18:22
@shardulc I don't think they have the same root cause but I'm interested in what parts of the code are affected by a reload. This would help figure out where to move the mail check code.

**Comment by jonorthwash** [comment] 2017-12-23 18:25
I think the desired behaviour is:
- report mail as it arrives (e.g., poll mail, like it polls SVN—I believe on receiving a ping, but there may be a better way to do this)
- on rejoin when there's a lot of new mail, perhaps only report the number of new messages (maybe if over 2 or something)

**Comment by Androbin** [comment] 2017-12-23 19:09
@jonorthwash There are basically two options:
* Active: Check on certain occasions or in intervals
* Passive: Listening for a "ping"

Currently, we check actively on reload.
It would be great to do it passively.

* We can check on more occasions (someone else joins the room)
* We can check in intervals (every couple of minutes or so)

**Comment by jonorthwash** [comment] 2017-12-24 00:08
What are the advantages between listening for a ping from the IRC server versus checking every so often?  It would be good to have fairly instantaneous notifications (i.e., no more than a few minutes' delay), but mailing list emails aren't super frequent either.

**Comment by Androbin** [comment] 2017-12-24 00:30
> What are the advantages between listening for a ping from the IRC server versus checking every so often?

Active checking would:
* give the most control
* be as fast as we want (maybe don't overdo it)
* either require a dedicated thread or be kicked off by various event handlers

Passive checking would:
* presumably be easiest to set up
* be subject to possible delivery delays

**Comment by jonorthwash** [comment] 2017-12-26 22:19
Yeah, I know it works sometimes.  But it randomly (and inconsistently) stops working, and then on join it'll start posting all sorts of stuff.  Perhaps grep the logs for the last time this happened, and see if the code's been updated since then?

**Comment by wei2912** [comment] 2017-12-27 06:51
BTW the more module should be a decent solution to reporting on mail sent
when there's a lot of new mail.

**Comment by wei2912** [comment] 2017-12-27 06:52
For reference, https://github.com/goavki/phenny/issues/159

**Comment by Androbin** [comment] 2017-12-27 15:35
Will do this as part of the next task.
Waiting for #284 to get merged.

**Comment by jonorthwash** [comment] 2017-12-27 19:37
I'm curious how this would work.  For example, on join begiak might say:
```
<begiak> 15 new mail messages
<begiak> 20 new commits to svn
```

When you type `.more`, how will it know which you mean?  Or how many to give you?  Might it be better to say `.show svn 3` or something?

**Comment by jonorthwash** [comment] 2017-12-27 19:38
> `.show svn 3`

Or even `.next svn 3`

**Comment by Androbin** [comment] 2017-12-27 19:44
Currently, messages are queued in the order they arive in.
If anything calls `add_messages` it's guaranteed that they come in a row.
But I do like @jonorthwash 's idea to be able to "tag" messages like this.
I might look into this as part of the next task.

**Comment by jonorthwash** [comment] 2017-12-28 03:03
The issue isn't the order they're displayed in, but preventing it from showing one line for each of the 15 new messages that it hasn't reported.

**Comment by Androbin** [comment] 2017-12-28 13:49
The first message you get from `.more` is from whatever module calls `add_messages` first.
Meaning, it won't print "one line for each of the 15 new messages that it hasn't reported".
But I think nonetheless that the syntax you proposed will be helpful.

**Comment by wei2912** [comment] 2017-12-28 14:53
Agreed. I will create an issue to add in this functionality.

**Comment by Androbin** [comment] 2017-12-28 14:54
@wei2912 Already have -> #292

**Comment by Androbin** [comment] 2017-12-29 01:42
@jonorthwash Seems like somehow, the `mailing_list_timer` isn't restarted.
But without a working configuration I can't tell why that is exactly.
Are there any known occasions of `login` failing for no good reason?

**Comment by jonorthwash** [comment] 2017-12-29 20:06
I'm not sure about `login`.  How would I be able to tell?

**Comment by Androbin** [comment] 2018-03-11 18:09
Did [implementing `.more` for `check_mail`](https://github.com/apertium/phenny/commit/32f3d52972d8cfd069bec15be4080e641ea7340c) get rid of the flooding?

**Comment by Androbin** [comment] 2018-08-14 13:01
Did [implementing `.more` for `check_mail`](https://github.com/apertium/phenny/commit/32f3d52972d8cfd069bec15be4080e641ea7340c) get rid of the flooding?

**Comment by scoopgracie** [comment] 2020-03-13 02:48
This seems to no longer be an issue.

**Closed by scoopgracie** 2020-03-13 02:48 UTC
Labels: bug, flood-control, modules
